// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	Book             *book
	ReviewAppealInfo *reviewAppealInfo
	ReviewInfo       *reviewInfo
	ReviewReplyInfo  *reviewReplyInfo
	Sequence         *sequence
	ShortURLMap      *shortURLMap
	Spider           *spider
	User             *user
	UserModel        *userModel
	Usertable        *usertable
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Book = &Q.Book
	ReviewAppealInfo = &Q.ReviewAppealInfo
	ReviewInfo = &Q.ReviewInfo
	ReviewReplyInfo = &Q.ReviewReplyInfo
	Sequence = &Q.Sequence
	ShortURLMap = &Q.ShortURLMap
	Spider = &Q.Spider
	User = &Q.User
	UserModel = &Q.UserModel
	Usertable = &Q.Usertable
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		Book:             newBook(db, opts...),
		ReviewAppealInfo: newReviewAppealInfo(db, opts...),
		ReviewInfo:       newReviewInfo(db, opts...),
		ReviewReplyInfo:  newReviewReplyInfo(db, opts...),
		Sequence:         newSequence(db, opts...),
		ShortURLMap:      newShortURLMap(db, opts...),
		Spider:           newSpider(db, opts...),
		User:             newUser(db, opts...),
		UserModel:        newUserModel(db, opts...),
		Usertable:        newUsertable(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Book             book
	ReviewAppealInfo reviewAppealInfo
	ReviewInfo       reviewInfo
	ReviewReplyInfo  reviewReplyInfo
	Sequence         sequence
	ShortURLMap      shortURLMap
	Spider           spider
	User             user
	UserModel        userModel
	Usertable        usertable
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Book:             q.Book.clone(db),
		ReviewAppealInfo: q.ReviewAppealInfo.clone(db),
		ReviewInfo:       q.ReviewInfo.clone(db),
		ReviewReplyInfo:  q.ReviewReplyInfo.clone(db),
		Sequence:         q.Sequence.clone(db),
		ShortURLMap:      q.ShortURLMap.clone(db),
		Spider:           q.Spider.clone(db),
		User:             q.User.clone(db),
		UserModel:        q.UserModel.clone(db),
		Usertable:        q.Usertable.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Book:             q.Book.replaceDB(db),
		ReviewAppealInfo: q.ReviewAppealInfo.replaceDB(db),
		ReviewInfo:       q.ReviewInfo.replaceDB(db),
		ReviewReplyInfo:  q.ReviewReplyInfo.replaceDB(db),
		Sequence:         q.Sequence.replaceDB(db),
		ShortURLMap:      q.ShortURLMap.replaceDB(db),
		Spider:           q.Spider.replaceDB(db),
		User:             q.User.replaceDB(db),
		UserModel:        q.UserModel.replaceDB(db),
		Usertable:        q.Usertable.replaceDB(db),
	}
}

type queryCtx struct {
	Book             IBookDo
	ReviewAppealInfo IReviewAppealInfoDo
	ReviewInfo       IReviewInfoDo
	ReviewReplyInfo  IReviewReplyInfoDo
	Sequence         ISequenceDo
	ShortURLMap      IShortURLMapDo
	Spider           ISpiderDo
	User             IUserDo
	UserModel        IUserModelDo
	Usertable        IUsertableDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Book:             q.Book.WithContext(ctx),
		ReviewAppealInfo: q.ReviewAppealInfo.WithContext(ctx),
		ReviewInfo:       q.ReviewInfo.WithContext(ctx),
		ReviewReplyInfo:  q.ReviewReplyInfo.WithContext(ctx),
		Sequence:         q.Sequence.WithContext(ctx),
		ShortURLMap:      q.ShortURLMap.WithContext(ctx),
		Spider:           q.Spider.WithContext(ctx),
		User:             q.User.WithContext(ctx),
		UserModel:        q.UserModel.WithContext(ctx),
		Usertable:        q.Usertable.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
