// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"review-service/internal/data/model"
)

func newUserModel(db *gorm.DB, opts ...gen.DOOption) userModel {
	_userModel := userModel{}

	_userModel.userModelDo.UseDB(db, opts...)
	_userModel.userModelDo.UseModel(&model.UserModel{})

	tableName := _userModel.userModelDo.TableName()
	_userModel.ALL = field.NewAsterisk(tableName)
	_userModel.UID = field.NewInt64(tableName, "uid")
	_userModel.Userame = field.NewString(tableName, "userame")
	_userModel.Loginname = field.NewString(tableName, "loginname")
	_userModel.Dutydate = field.NewTime(tableName, "dutydate")

	_userModel.fillFieldMap()

	return _userModel
}

type userModel struct {
	userModelDo userModelDo

	ALL       field.Asterisk
	UID       field.Int64
	Userame   field.String
	Loginname field.String
	Dutydate  field.Time

	fieldMap map[string]field.Expr
}

func (u userModel) Table(newTableName string) *userModel {
	u.userModelDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userModel) As(alias string) *userModel {
	u.userModelDo.DO = *(u.userModelDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userModel) updateTableName(table string) *userModel {
	u.ALL = field.NewAsterisk(table)
	u.UID = field.NewInt64(table, "uid")
	u.Userame = field.NewString(table, "userame")
	u.Loginname = field.NewString(table, "loginname")
	u.Dutydate = field.NewTime(table, "dutydate")

	u.fillFieldMap()

	return u
}

func (u *userModel) WithContext(ctx context.Context) IUserModelDo {
	return u.userModelDo.WithContext(ctx)
}

func (u userModel) TableName() string { return u.userModelDo.TableName() }

func (u userModel) Alias() string { return u.userModelDo.Alias() }

func (u userModel) Columns(cols ...field.Expr) gen.Columns { return u.userModelDo.Columns(cols...) }

func (u *userModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userModel) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 4)
	u.fieldMap["uid"] = u.UID
	u.fieldMap["userame"] = u.Userame
	u.fieldMap["loginname"] = u.Loginname
	u.fieldMap["dutydate"] = u.Dutydate
}

func (u userModel) clone(db *gorm.DB) userModel {
	u.userModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userModel) replaceDB(db *gorm.DB) userModel {
	u.userModelDo.ReplaceDB(db)
	return u
}

type userModelDo struct{ gen.DO }

type IUserModelDo interface {
	gen.SubQuery
	Debug() IUserModelDo
	WithContext(ctx context.Context) IUserModelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserModelDo
	WriteDB() IUserModelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserModelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserModelDo
	Not(conds ...gen.Condition) IUserModelDo
	Or(conds ...gen.Condition) IUserModelDo
	Select(conds ...field.Expr) IUserModelDo
	Where(conds ...gen.Condition) IUserModelDo
	Order(conds ...field.Expr) IUserModelDo
	Distinct(cols ...field.Expr) IUserModelDo
	Omit(cols ...field.Expr) IUserModelDo
	Join(table schema.Tabler, on ...field.Expr) IUserModelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserModelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserModelDo
	Group(cols ...field.Expr) IUserModelDo
	Having(conds ...gen.Condition) IUserModelDo
	Limit(limit int) IUserModelDo
	Offset(offset int) IUserModelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserModelDo
	Unscoped() IUserModelDo
	Create(values ...*model.UserModel) error
	CreateInBatches(values []*model.UserModel, batchSize int) error
	Save(values ...*model.UserModel) error
	First() (*model.UserModel, error)
	Take() (*model.UserModel, error)
	Last() (*model.UserModel, error)
	Find() ([]*model.UserModel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserModel, err error)
	FindInBatches(result *[]*model.UserModel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserModel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserModelDo
	Assign(attrs ...field.AssignExpr) IUserModelDo
	Joins(fields ...field.RelationField) IUserModelDo
	Preload(fields ...field.RelationField) IUserModelDo
	FirstOrInit() (*model.UserModel, error)
	FirstOrCreate() (*model.UserModel, error)
	FindByPage(offset int, limit int) (result []*model.UserModel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserModelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userModelDo) Debug() IUserModelDo {
	return u.withDO(u.DO.Debug())
}

func (u userModelDo) WithContext(ctx context.Context) IUserModelDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userModelDo) ReadDB() IUserModelDo {
	return u.Clauses(dbresolver.Read)
}

func (u userModelDo) WriteDB() IUserModelDo {
	return u.Clauses(dbresolver.Write)
}

func (u userModelDo) Session(config *gorm.Session) IUserModelDo {
	return u.withDO(u.DO.Session(config))
}

func (u userModelDo) Clauses(conds ...clause.Expression) IUserModelDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userModelDo) Returning(value interface{}, columns ...string) IUserModelDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userModelDo) Not(conds ...gen.Condition) IUserModelDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userModelDo) Or(conds ...gen.Condition) IUserModelDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userModelDo) Select(conds ...field.Expr) IUserModelDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userModelDo) Where(conds ...gen.Condition) IUserModelDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userModelDo) Order(conds ...field.Expr) IUserModelDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userModelDo) Distinct(cols ...field.Expr) IUserModelDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userModelDo) Omit(cols ...field.Expr) IUserModelDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userModelDo) Join(table schema.Tabler, on ...field.Expr) IUserModelDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserModelDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userModelDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserModelDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userModelDo) Group(cols ...field.Expr) IUserModelDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userModelDo) Having(conds ...gen.Condition) IUserModelDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userModelDo) Limit(limit int) IUserModelDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userModelDo) Offset(offset int) IUserModelDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserModelDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userModelDo) Unscoped() IUserModelDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userModelDo) Create(values ...*model.UserModel) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userModelDo) CreateInBatches(values []*model.UserModel, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userModelDo) Save(values ...*model.UserModel) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userModelDo) First() (*model.UserModel, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModel), nil
	}
}

func (u userModelDo) Take() (*model.UserModel, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModel), nil
	}
}

func (u userModelDo) Last() (*model.UserModel, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModel), nil
	}
}

func (u userModelDo) Find() ([]*model.UserModel, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserModel), err
}

func (u userModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserModel, err error) {
	buf := make([]*model.UserModel, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userModelDo) FindInBatches(result *[]*model.UserModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userModelDo) Attrs(attrs ...field.AssignExpr) IUserModelDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userModelDo) Assign(attrs ...field.AssignExpr) IUserModelDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userModelDo) Joins(fields ...field.RelationField) IUserModelDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userModelDo) Preload(fields ...field.RelationField) IUserModelDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userModelDo) FirstOrInit() (*model.UserModel, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModel), nil
	}
}

func (u userModelDo) FirstOrCreate() (*model.UserModel, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModel), nil
	}
}

func (u userModelDo) FindByPage(offset int, limit int) (result []*model.UserModel, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userModelDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userModelDo) Delete(models ...*model.UserModel) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userModelDo) withDO(do gen.Dao) *userModelDo {
	u.DO = *do.(*gen.DO)
	return u
}
