// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"review-service/internal/data/model"
)

func newUsertable(db *gorm.DB, opts ...gen.DOOption) usertable {
	_usertable := usertable{}

	_usertable.usertableDo.UseDB(db, opts...)
	_usertable.usertableDo.UseModel(&model.Usertable{})

	tableName := _usertable.usertableDo.TableName()
	_usertable.ALL = field.NewAsterisk(tableName)
	_usertable.ID = field.NewInt32(tableName, "id")
	_usertable.Username = field.NewString(tableName, "username")
	_usertable.Password = field.NewString(tableName, "password")
	_usertable.Email = field.NewString(tableName, "email")
	_usertable.Role = field.NewString(tableName, "role")
	_usertable.Status = field.NewInt32(tableName, "status")
	_usertable.Header = field.NewString(tableName, "header")

	_usertable.fillFieldMap()

	return _usertable
}

type usertable struct {
	usertableDo usertableDo

	ALL      field.Asterisk
	ID       field.Int32
	Username field.String
	Password field.String
	Email    field.String
	Role     field.String
	Status   field.Int32
	Header   field.String

	fieldMap map[string]field.Expr
}

func (u usertable) Table(newTableName string) *usertable {
	u.usertableDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u usertable) As(alias string) *usertable {
	u.usertableDo.DO = *(u.usertableDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *usertable) updateTableName(table string) *usertable {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.Username = field.NewString(table, "username")
	u.Password = field.NewString(table, "password")
	u.Email = field.NewString(table, "email")
	u.Role = field.NewString(table, "role")
	u.Status = field.NewInt32(table, "status")
	u.Header = field.NewString(table, "header")

	u.fillFieldMap()

	return u
}

func (u *usertable) WithContext(ctx context.Context) IUsertableDo {
	return u.usertableDo.WithContext(ctx)
}

func (u usertable) TableName() string { return u.usertableDo.TableName() }

func (u usertable) Alias() string { return u.usertableDo.Alias() }

func (u usertable) Columns(cols ...field.Expr) gen.Columns { return u.usertableDo.Columns(cols...) }

func (u *usertable) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *usertable) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 7)
	u.fieldMap["id"] = u.ID
	u.fieldMap["username"] = u.Username
	u.fieldMap["password"] = u.Password
	u.fieldMap["email"] = u.Email
	u.fieldMap["role"] = u.Role
	u.fieldMap["status"] = u.Status
	u.fieldMap["header"] = u.Header
}

func (u usertable) clone(db *gorm.DB) usertable {
	u.usertableDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u usertable) replaceDB(db *gorm.DB) usertable {
	u.usertableDo.ReplaceDB(db)
	return u
}

type usertableDo struct{ gen.DO }

type IUsertableDo interface {
	gen.SubQuery
	Debug() IUsertableDo
	WithContext(ctx context.Context) IUsertableDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUsertableDo
	WriteDB() IUsertableDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUsertableDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUsertableDo
	Not(conds ...gen.Condition) IUsertableDo
	Or(conds ...gen.Condition) IUsertableDo
	Select(conds ...field.Expr) IUsertableDo
	Where(conds ...gen.Condition) IUsertableDo
	Order(conds ...field.Expr) IUsertableDo
	Distinct(cols ...field.Expr) IUsertableDo
	Omit(cols ...field.Expr) IUsertableDo
	Join(table schema.Tabler, on ...field.Expr) IUsertableDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUsertableDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUsertableDo
	Group(cols ...field.Expr) IUsertableDo
	Having(conds ...gen.Condition) IUsertableDo
	Limit(limit int) IUsertableDo
	Offset(offset int) IUsertableDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUsertableDo
	Unscoped() IUsertableDo
	Create(values ...*model.Usertable) error
	CreateInBatches(values []*model.Usertable, batchSize int) error
	Save(values ...*model.Usertable) error
	First() (*model.Usertable, error)
	Take() (*model.Usertable, error)
	Last() (*model.Usertable, error)
	Find() ([]*model.Usertable, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Usertable, err error)
	FindInBatches(result *[]*model.Usertable, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Usertable) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUsertableDo
	Assign(attrs ...field.AssignExpr) IUsertableDo
	Joins(fields ...field.RelationField) IUsertableDo
	Preload(fields ...field.RelationField) IUsertableDo
	FirstOrInit() (*model.Usertable, error)
	FirstOrCreate() (*model.Usertable, error)
	FindByPage(offset int, limit int) (result []*model.Usertable, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUsertableDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u usertableDo) Debug() IUsertableDo {
	return u.withDO(u.DO.Debug())
}

func (u usertableDo) WithContext(ctx context.Context) IUsertableDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u usertableDo) ReadDB() IUsertableDo {
	return u.Clauses(dbresolver.Read)
}

func (u usertableDo) WriteDB() IUsertableDo {
	return u.Clauses(dbresolver.Write)
}

func (u usertableDo) Session(config *gorm.Session) IUsertableDo {
	return u.withDO(u.DO.Session(config))
}

func (u usertableDo) Clauses(conds ...clause.Expression) IUsertableDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u usertableDo) Returning(value interface{}, columns ...string) IUsertableDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u usertableDo) Not(conds ...gen.Condition) IUsertableDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u usertableDo) Or(conds ...gen.Condition) IUsertableDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u usertableDo) Select(conds ...field.Expr) IUsertableDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u usertableDo) Where(conds ...gen.Condition) IUsertableDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u usertableDo) Order(conds ...field.Expr) IUsertableDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u usertableDo) Distinct(cols ...field.Expr) IUsertableDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u usertableDo) Omit(cols ...field.Expr) IUsertableDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u usertableDo) Join(table schema.Tabler, on ...field.Expr) IUsertableDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u usertableDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUsertableDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u usertableDo) RightJoin(table schema.Tabler, on ...field.Expr) IUsertableDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u usertableDo) Group(cols ...field.Expr) IUsertableDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u usertableDo) Having(conds ...gen.Condition) IUsertableDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u usertableDo) Limit(limit int) IUsertableDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u usertableDo) Offset(offset int) IUsertableDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u usertableDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUsertableDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u usertableDo) Unscoped() IUsertableDo {
	return u.withDO(u.DO.Unscoped())
}

func (u usertableDo) Create(values ...*model.Usertable) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u usertableDo) CreateInBatches(values []*model.Usertable, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u usertableDo) Save(values ...*model.Usertable) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u usertableDo) First() (*model.Usertable, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Usertable), nil
	}
}

func (u usertableDo) Take() (*model.Usertable, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Usertable), nil
	}
}

func (u usertableDo) Last() (*model.Usertable, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Usertable), nil
	}
}

func (u usertableDo) Find() ([]*model.Usertable, error) {
	result, err := u.DO.Find()
	return result.([]*model.Usertable), err
}

func (u usertableDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Usertable, err error) {
	buf := make([]*model.Usertable, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u usertableDo) FindInBatches(result *[]*model.Usertable, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u usertableDo) Attrs(attrs ...field.AssignExpr) IUsertableDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u usertableDo) Assign(attrs ...field.AssignExpr) IUsertableDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u usertableDo) Joins(fields ...field.RelationField) IUsertableDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u usertableDo) Preload(fields ...field.RelationField) IUsertableDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u usertableDo) FirstOrInit() (*model.Usertable, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Usertable), nil
	}
}

func (u usertableDo) FirstOrCreate() (*model.Usertable, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Usertable), nil
	}
}

func (u usertableDo) FindByPage(offset int, limit int) (result []*model.Usertable, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u usertableDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u usertableDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u usertableDo) Delete(models ...*model.Usertable) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *usertableDo) withDO(do gen.Dao) *usertableDo {
	u.DO = *do.(*gen.DO)
	return u
}
