// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSequence = "sequence"

// Sequence 序号表
type Sequence struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Stub      string    `gorm:"column:stub;not null" json:"stub"`
	Timestamp time.Time `gorm:"column:timestamp;not null;default:CURRENT_TIMESTAMP" json:"timestamp"`
}

// TableName Sequence's table name
func (*Sequence) TableName() string {
	return TableNameSequence
}
