// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSpider = "spider"

// Spider mapped from table <spider>
type Spider struct {
	ID           int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title        *string `gorm:"column:title" json:"title"`
	Link         *string `gorm:"column:link" json:"link"`
	Imgsrc       *string `gorm:"column:imgsrc" json:"imgsrc"`
	Rating       *string `gorm:"column:rating" json:"rating"`
	Judgenum     *string `gorm:"column:judgenum" json:"judgenum"`
	Inq          *string `gorm:"column:inq" json:"inq"`
	Director     *string `gorm:"column:director" json:"director"`
	Scriptwriter *string `gorm:"column:scriptwriter" json:"scriptwriter"`
	Type         *string `gorm:"column:type" json:"type"`
	Status       *string `gorm:"column:status" json:"status"`
	Language     *string `gorm:"column:language" json:"language"`
	Date         *string `gorm:"column:date" json:"date"`
	Time         *string `gorm:"column:time" json:"time"`
}

// TableName Spider's table name
func (*Spider) TableName() string {
	return TableNameSpider
}
