// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUsertable = "usertable"

// Usertable mapped from table <usertable>
type Usertable struct {
	ID       int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username *string `gorm:"column:username" json:"username"`
	Password *string `gorm:"column:password" json:"password"`
	Email    *string `gorm:"column:email" json:"email"`
	Role     *string `gorm:"column:role;default:普通用户" json:"role"`
	Status   *int32  `gorm:"column:status;default:1" json:"status"`
	Header   *string `gorm:"column:header" json:"header"`
}

// TableName Usertable's table name
func (*Usertable) TableName() string {
	return TableNameUsertable
}
