// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserModel = "user_models"

// UserModel mapped from table <user_models>
type UserModel struct {
	UID       *int64     `gorm:"column:uid" json:"uid"`
	Userame   string     `gorm:"column:userame;primaryKey" json:"userame"`
	Loginname *string    `gorm:"column:loginname;default:test" json:"loginname"`
	Dutydate  *time.Time `gorm:"column:dutydate" json:"dutydate"`
}

// TableName UserModel's table name
func (*UserModel) TableName() string {
	return TableNameUserModel
}
